[build]
standard = "c++17"
type = "executable"

[links]
tomlplusplus = { git = "https://github.com/marzer/tomlplusplus.git" }

[node]
authors = ["Your Name <your.email@example.com>"]
description = "A graph-based C++ package manager"
license = "MIT"
name = "nexus"
readme = "README.md"
version = "0.1.0"

[profile]
debug = { lto = false, opt-level = 0 }
release = { lto = true, opt-level = 3, strip = true }
test = { lto = false, opt-level = 1 }

[toolchain]
compiler = "clang++"
target = "x86_64-pc-windows-msvc"

